### ISSUE TITLE
File not found Error

### ISSUE THREAD

**Issue by abubakar0015** [radioactive11/ALPR-India#1]
i'm trying to  run this project. but facing this issue 

`Traceback (most recent call last):
  File "D:/ALPR-India-master/plate.py", line 4, in <module>
    import darknet
  File "D:\ALPR-India-master\darknet.py", line 86, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "D:\InstalledPrograms\Anaconda3\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\ALPR-India-master\yolo_cpp_dll.dll' (or one of its dependencies). Try using the full path with constructor syntax.
`

**Comment by radioactive11** [comment]
> Window 10 64-bit . Yes file is already in the repo. But still this error . I'm also trying to build another github project. But facing this same error. Please help me to resolve this. thanks

I had made this project targeting Windows. I'll soon be releasing a version which is compatible with all operating systems

**Comment by abubakar0015** [comment]
I'm also using windows. Window 10
