### ISSUE TITLE
No DLL error

### ISSUE THREAD

**Issue by Shreesha5102** [radioactive11/ALPR-India#3]
D:\Shreesha\ALPR-India>python plate.py
Traceback (most recent call last):
  File "D:\Shreesha\ALPR-India\darknet.py", line 118, in <module>
    raise ValueError("NoDLL")
ValueError: NoDLL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "plate.py", line 4, in <module>
    import darknet
  File "D:\Shreesha\ALPR-India\darknet.py", line 128, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\Users\Evilslayer\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by Shreesha5102** [comment]
Any help would be appreciated

**Comment by radioactive11** [comment]
I'll look into shortly

**Comment by radioactive11** [comment]
Added required DLLs in this [commit](https://github.com/radioactive11/ALPR-India/commit/32dd9a4b9633c2b5dd417ead372aa110b336e32e)
